### ISSUE TITLE
Fix compatibility for Symfony 4.x

### ISSUE THREAD

**Issue by jakubtobiasz** [PolishSymfonyCommunity/SymfonyMockerContainer#20]
After the last changes merged support for Symfony 4.4 is dead.
![image](https://user-images.githubusercontent.com/80641364/195828839-62f158db-b7e2-424f-ad31-f264a15475a0.png)

As we still need a working 4.4 for Sylius 1.11 and the last changes made BC break, here is my list of suggestions to do:

- [ ] Remove the last two releases OR revert the changes and release a patch version
- [ ]  Add GHA for Symfony `^4.0` and `^5.0` as it has been working
- [ ] Create `1.x` branch with the previous state and new GHA
- [ ] On the master branch drop Symfony `^4.0` support and create `2.x` release

Then in Sylius, we'll be able to add `"polishsymfonycommunity/symfony-mocker-container": "^1.0|^2.0"`.

**Comment by jakubtobiasz** [comment]
@jakzal can you create `1.x` branch? I'll open proper PRs, @Zales0123 today is offline 🖖🏻.

**Comment by jakzal** [comment]
Thanks for reporting and coming up with a plan!

We probably shouldn't remove releases.

Is it possible to support Symfony 4-6 in 1.0 rather than releasing 2.0?

**Comment by jakubtobiasz** [comment]
@jakzal afaik no, the contract has changed (previously `string` type hasn't been required) and we have to conform it. I believe if Mateusz added this type in PR adding support for Symfony 6 it was required, so I see no way to do it in a single version :/.

**Comment by jakzal** [comment]
Would it work if we had two versions? We’d first rollback and make a release for older Symfony versions, then we’d add support for Symfony 6, drop incompatible versions and make a new release. This package isn’t changing in functionality so there’s no need to branch.

**Comment by jakubtobiasz** [comment]
@jakzal considering the package doesn't change too often we can do it that way :P. Just the last two tags should be `2.0`.

**Comment by jakubtobiasz** [comment]
The issue is fixed, so I'm closing it :P.
